apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: ipvlan-conf
spec:
  config: '{
    "cniVersion": "0.3.0",
    "type": "ipvlan",
    "name": "net-ipvlan",
    "master": "eth0",
    "mode": "l3",
    "ipam": {
          "type": "host-local",
          "subnet": "100.73.14.0/24",
          "rangeStart": "100.73.14.20",
          "rangeEnd": "100.73.14.149",
          "gateway": "100.73.14.254",
          "routes": [
              { "dst": "100.73.14.0/24", "gw": "100.73.14.254" }
          ]
    }
  }'
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: ipvlan-conf1
spec:
  config: '{
    "cniVersion": "0.3.0",
    "type": "ipvlan",
    "name": "net-ipvlan",
    "master": "eth0",
    "mode": "l3",
    "ipam": {
          "type": "host-local",
          "subnet": "100.73.14.0/24",
          "rangeStart": "100.73.14.160",
          "rangeEnd": "100.73.14.200",
          "gateway": "100.73.14.254",
          "routes": [
              { "dst": "100.73.14.0/24", "gw": "100.73.14.254" }
          ]
    }
  }'
